#!/usr/bin/env bash
# Generate THIRD_PARTY_LICENSES by auto-discovering LICENSE files.
# Usage: ./scripts/generate-licenses.sh
#
# How it works:
#   1. Scans SCAN_DIRS for LICENSE* files and includes them automatically
#   2. Manually-added entries in the OVERRIDES section are merged in
#
# To add a new bundled dependency:
#   Place a LICENSE file next to it (e.g. Resources/foo/LICENSE).
#   The script picks it up automatically on the next run.

set -euo pipefail
cd "$(dirname "$0")/.."

OUTPUT="THIRD_PARTY_LICENSES"
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

# ─── config ─────────────────────────────────────────────────────────
# Glob patterns to scan (relative to repo root).
# Each matching LICENSE file is included with its parent dir as the name.
SCAN_PATTERNS=(
  "deps/*/LICENSE*"
  "deps/*/vendor/*/LICENSE*"
  "Resources/*/LICENSE*"
)

# Directories to skip (self-managed licenses like Ghostty's vendored deps
# that are transitively included and don't need separate listing, etc.)
# Use parent directory basename for matching.
SKIP_DIRS=()

# ─── helpers ────────────────────────────────────────────────────────
separator() {
  printf '%s\n\n' "$(printf '=%.0s' {1..72})" >> "$TMP"
}

emit_entry() {
  local name="$1" license_file="$2"

  printf '%s\n' "$name" >> "$TMP"
  printf '\n' >> "$TMP"
  cat "$license_file" >> "$TMP"
  printf '\n' >> "$TMP"
  separator
}

should_skip() {
  local dir_name="$1"
  for skip in "${SKIP_DIRS[@]}"; do
    [[ "$dir_name" == "$skip" ]] && return 0
  done
  return 1
}

# ─── header ─────────────────────────────────────────────────────────
cat > "$TMP" << 'HEADER'
THIRD-PARTY SOFTWARE LICENSES

This file lists the licenses of third-party software bundled with or
linked by Trellis. It is auto-generated by scripts/generate-licenses.sh.

HEADER
separator

# ─── auto-discover ──────────────────────────────────────────────────
discovered=0
seen_dirs=()

for pattern in "${SCAN_PATTERNS[@]}"; do
  # nullglob: skip if no match
  for license_file in $pattern; do
    [[ -f "$license_file" ]] || continue

    dir="$(dirname "$license_file")"
    dir_name="$(basename "$dir")"

    # dedup (same dir may match multiple patterns)
    for seen in "${seen_dirs[@]+"${seen_dirs[@]}"}"; do
      [[ "$seen" == "$dir" ]] && continue 2
    done
    seen_dirs+=("$dir")

    if should_skip "$dir_name"; then
      continue
    fi

    emit_entry "$dir_name" "$license_file"
    discovered=$((discovered + 1))
  done
done

# ─── done ───────────────────────────────────────────────────────────
mv "$TMP" "$OUTPUT"
echo "Generated $OUTPUT ($discovered entries discovered)"
